"""Declare runtime dependencies

These are needed for local dev, and users must install them as well.
See https://docs.bazel.build/versions/main/skylark/deploying.html#dependencies
"""

load("//mylang/private:toolchains_repo.bzl", "PLATFORMS", "toolchains_repo")
load("//mylang/private:versions.bzl", "TOOL_VERSIONS")

_DOC = "Fetch external tools needed for mylang toolchain"
_ATTRS = {
    "mylang_version": attr.string(mandatory = True, values = TOOL_VERSIONS.keys()),
    "platform": attr.string(mandatory = True, values = PLATFORMS.keys()),
}

def _mylang_repo_impl(repository_ctx):
    url = "https://github.com/someorg/someproject/releases/download/v{0}/mylang-{1}.zip".format(
        repository_ctx.attr.mylang_version,
        repository_ctx.attr.platform,
    )
    repository_ctx.download_and_extract(
        url = url,
        integrity = TOOL_VERSIONS[repository_ctx.attr.mylang_version][repository_ctx.attr.platform],
    )
    ext = ".exe" if repository_ctx.attr.platform.find("windows") >= 0 else ""
    build_content = """# Generated by mylang/repositories.bzl
load("@com_myorg_rules_mylang//mylang:toolchain.bzl", "mylang_toolchain")

mylang_toolchain(
    name = "mylang_toolchain",
    target_tool = "mylang_tool{ext}",
)
""".format(ext = ext)

    # Base BUILD file for this repository
    repository_ctx.file("BUILD.bazel", build_content)

    # Bazel <8.3.0 lacks rctx.repo_metadata
    if not hasattr(repository_ctx, "repo_metadata"):
        return None

    # https://bazel.build/rules/lib/builtins/repository_ctx#repo_metadata
    # Indicate whether the repo can be reproducibly refetched, allowing it
    # to be cached across workspaces.
    return repository_ctx.repo_metadata(reproducible = True)

mylang_repositories = repository_rule(
    _mylang_repo_impl,
    doc = _DOC,
    attrs = _ATTRS,
)

# Wrapper macro around everything above, this is the primary API
def mylang_register_toolchains(name, **kwargs):
    """Convenience macro for users which does typical setup.

    - create a repository for each built-in platform like "mylang_linux_amd64"
    - TODO: create a convenience repository for the host platform like "mylang_host"
    - create a repository exposing toolchains for each platform like "mylang_platforms"
    Users can avoid this macro and do these steps themselves, if they want more control.

    Args:
        name: base name for all created repos, like "mylang1_14"
        **kwargs: passed to each mylang_repositories call
    """
    for platform in PLATFORMS.keys():
        mylang_repositories(
            name = name + "_" + platform,
            platform = platform,
            **kwargs
        )

    toolchains_repo(
        name = name + "_toolchains",
        user_repository_name = name,
    )
