# See https://github.com/bazel-contrib/publish-to-bcr#a-note-on-release-automation
# for guidance about whether to uncomment this section:
#
# fixedReleaser:
#   login: my_github_handle
#   email: me@my.org
