# Cut a release whenever a new tag is pushed to the repo.
name: Release

on:
  # Can be triggered from the tag.yaml workflow
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
  # Or, developers can manually push a tag from their clone
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@c9d6d1893b10a8d68584a6ba52c3dd35506486d0 # 2024-12-03
    with:
      release_files: rules_mylang-*.tar.gz
      tag_name: ${{ inputs.tag_name }}
